### ISSUE TITLE
Finish reservation module 

### ISSUE THREAD

**Issue by SailC** [SailC/miyabi#1]
Design and implement the flow of :

- [ ] The customers finish booking via dialog provided by conversational web form 

- [ ] web form sends `post` http request to the express server

- [ ] express server responds by sending rest api calls to MailChimp 

- [ ] MailChimp sends emails to the customers
